spring:
  thymeleaf:
    cache: false
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuki
    username: root
    password: qwe123
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    password: qwe123
server:
  max-http-header-size: 8192
  port: 3000
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.client: DEBUG
    org.springframework.web.socket.server: DEBUG